import './globals.css';

import Header from './components/Header';
import Provider from './components/Provider';

import { getServerSession } from 'next-auth';

export const metadata = {
  title: 'Google Auth Test',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body>
        <Provider session={session}>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  )
}
